FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y build-essential python3-dev gcc

COPY . .

CMD ["python", "main.py"]
